  name: Enhancement
  description: Suggest changes to the existing code. This is NOT for making suggestions for the game. It's for contributors to request code changes from other contributors, usually ones that have been discussed.
  title: "[ENHANCE] "
  labels: ['enhancement']
  body:
    - type: textarea
      attributes:
        label: Description
        description: Please describe the changes you would like to see. Give details on the current behavior vs. the goal behavior. If you have an idea of how specifically this change could be made, explain it.
